//
//  HomeRouter.swift
//  MyMovie
//
//  Created by tar on 27/2/2563 BE.
//  Copyright (c) 2563 jirawat.com. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol HomeRoutingLogic
{
  func routeToList(segue: UIStoryboardSegue?)
}

protocol HomeDataPassing
{
  var dataStore: HomeDataStore? { get }
}

class HomeRouter: NSObject, HomeRoutingLogic, HomeDataPassing
{
  weak var viewController: HomeViewController?
  var dataStore: HomeDataStore?
  
  // MARK: Routing
  
  func routeToList(segue: UIStoryboardSegue?)
  {
    if let segue = segue {
      let destinationVC = segue.destination as! ListViewController
      var destinationDS = destinationVC.router!.dataStore!
      passDataToList(source: dataStore!, destination: &destinationDS)
    } else {
      let storyboard = UIStoryboard(name: "Main", bundle: nil)
      let destinationVC = storyboard.instantiateViewController(withIdentifier: "ListViewController") as! ListViewController
      var destinationDS = destinationVC.router!.dataStore!
      passDataToList(source: dataStore!, destination: &destinationDS)
      navigateToList(source: viewController!, destination: destinationVC)
    }
  }

  // MARK: Navigation
  
  func navigateToList(source: HomeViewController, destination: ListViewController)
  {
    source.show(destination, sender: nil)
  }
  
  // MARK: Passing data
  
  func passDataToList(source: HomeDataStore, destination: inout ListDataStore)
  {
    destination.name = source.name
  }
}
