//
//  ProfilePresenter.swift
//  MyMovie
//
//  Created by tar on 27/2/2563 BE.
//  Copyright (c) 2563 jirawat.com. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProfilePresentationLogic
{
  func presentSomething(response: Profile.Something.Response)
}

class ProfilePresenter: ProfilePresentationLogic
{
  weak var viewController: ProfileDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Profile.Something.Response)
  {
    let viewModel = Profile.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
